"""initial schema

Revision ID: 56778ef625ab
Revises: 
Create Date: 2026-08-30 15:31:41.515584
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '56778ef625ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('art_works',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('artist', sa.String(length=128), nullable=False),
    sa.Column('year', sa.String(length=64), nullable=False),
    sa.Column('thumbnail', sa.String(length=256), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('alt', sa.String(length=256), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('article', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_withdrawn', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(title)) > 0 AND length(btrim(artist)) > 0 AND length(btrim(year)) > 0 AND length(btrim(thumbnail)) > 0 AND length(btrim(image)) > 0 AND length(btrim(alt)) > 0 AND length(btrim(source)) > 0 AND length(btrim(article)) > 0', name='ck_art_required_nonblank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('openid', sa.String(length=128), nullable=False),
    sa.Column('unionid', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unionid')
    )
    op.create_index(op.f('ix_users_openid'), 'users', ['openid'], unique=True)
    op.create_table('analytics_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('night_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ritual_date', sa.Date(), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('late_minutes', sa.Integer(), nullable=False),
    sa.Column('is_eligible', sa.Boolean(), nullable=False),
    sa.Column('resistance_reason', sa.String(length=128), nullable=True),
    sa.Column('gratitudes_enc', sa.LargeBinary(), nullable=True),
    sa.Column('plans_enc', sa.LargeBinary(), nullable=True),
    sa.Column('reward_revealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_draw_count', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ritual_date', name='uq_night_user_date')
    )
    op.create_index('ix_night_user_date', 'night_records', ['user_id', 'ritual_date'], unique=False)
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bedtime', sa.Time(), server_default=sa.text("'23:30'"), nullable=False),
    sa.Column('wake_time', sa.Time(), server_default=sa.text("'07:30'"), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'Asia/Shanghai'"), nullable=False),
    sa.Column('reduced_motion', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('night_record_id', sa.UUID(), nullable=False),
    sa.Column('art_id', sa.String(length=64), nullable=False),
    sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['art_id'], ['art_works.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['night_record_id'], ['night_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reward_user_awarded', 'rewards', ['user_id', 'awarded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reward_user_awarded', table_name='rewards')
    op.drop_table('rewards')
    op.drop_table('user_settings')
    op.drop_index('ix_night_user_date', table_name='night_records')
    op.drop_table('night_records')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_users_openid'), table_name='users')
    op.drop_table('users')
    op.drop_table('art_works')
    # ### end Alembic commands ###
